name: Experiment
on: 
  push:
    branches: [main]

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      with: { ref: debug }
    - name: List files
      run: ls
