name: Experiment
on: 
  push:
    branches: [main]

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: List files
      run: ls
    - name: pwd
      run: pwd
    - name: setup python
      with:
        python-version: 3.8 #install the python needed
    - name: execute py script
      run:
        python testPython/hellol.py
    
